### ISSUE TITLE
Spelfout in de doelgroepen vaccin plot

### ISSUE THREAD

**Issue by sonar98** [YorickBleijenberg/COVID_data_RIVM_Netherlands#1]
Hoi Yorick,

Er staat een spelfoutje in de plot over de vaccinatie van doelgroepen.
Nu staat er:
medichte indicatie

Moet denk ik zijn:
medische indicatie

![image](https://user-images.githubusercontent.com/645403/104903055-d7bae300-597f-11eb-955f-65a91ab3c658.png)

**Comment by YorickBleijenberg** [comment]
Dank voor de feedback!
Inderdaad, ik heb het gefixt!
