### ISSUE TITLE
Update leverschema

### ISSUE THREAD

**Issue by laurens-van-wijngaarden** [YorickBleijenberg/COVID_data_RIVM_Netherlands#2]
In de brief aan de TK (https://www.tweedekamer.nl/kamerstukken/brieven_regering/detail?id=2021Z01041&did=2021D02515) staat een geupdate leverschema.

![image](https://user-images.githubusercontent.com/59054321/105371187-a3a42400-5c04-11eb-94ad-e03336d5d0d5.png)

**Comment by YorickBleijenberg** [comment]
Dank voor de heads-up.
Ik ben al druk bezig met de verwerking!
